### ISSUE TITLE
Null pointer exception after executing command 

### ISSUE THREAD

**Issue by Rohit-Medpalli123** [qa-guru/allure-notifications#126]
hi,I am facing below issue after executing  command --> java "-DconfigFile=notifications.json" -jar allure-notifications.jar

ubuntu@software-qa-testing-dev:/opt/automation/dev/repos/apiautomation$ java "-DconfigFile=notifications.json" -jar allure-notifications.jar
2022-08-20 15:12:22 INFO  Application:20 - Start...
2022-08-20 15:12:22 INFO  JSON:22 - Parsing *.json file by path notifications.json
2022-08-20 15:12:22 INFO  Notification:20 - Sending message...
2022-08-20 15:12:22 INFO  Chart:22 - Creating chart...
2022-08-20 15:12:22 INFO  ChartBuilder:13 - Creating chart with title APIAutomationTest...
2022-08-20 15:12:22 INFO  ChartBuilder:19 - Done.
2022-08-20 15:12:22 INFO  Chart:24 - Adding legend to chart...
2022-08-20 15:12:22 INFO  Chart:26 - Adding view to chart...
2022-08-20 15:12:22 INFO  Chart:28 - Adding series to chart...
2022-08-20 15:12:22 INFO  SummaryMapper:24 - Mapping widgets/summary.json to Summary object
2022-08-20 15:12:22 INFO  JSON:22 - Parsing *.json file by path /opt/automation/dev/repos/apiautomation/Results/allure-reports/latest/widgets/summary.json
2022-08-20 15:12:22 ERROR Application:32 -
java.lang.NullPointerException
	at guru.qa.allure.notifications.util.ResourcesUtil.resourcesPath(ResourcesUtil.java:10)
	at guru.qa.allure.notifications.mapper.LegendMapper.map(LegendMapper.java:26)
	at guru.qa.allure.notifications.chart.ChartSeries.addSeriesTo(ChartSeries.java:26)
	at guru.qa.allure.notifications.chart.Chart.createChart(Chart.java:29)
	at guru.qa.allure.notifications.clients.Notification.send(Notification.java:22)
	at guru.qa.allure.notifications.Application.startApplication(Application.java:30)
	at guru.qa.allure.notifications.Application.main(Application.java:16)

**Comment by svasenkov** [comment]
**Triage (5.0 catch-up window):** leaving open.

- **5.0.* Java freeze** (through 5.0.8 on master): bugfix / security only — candidates for a targeted jar patch if still reproducible.
- **6.0 TypeScript** line (separate PR after versioning fix): preferred home for larger rewrites / new messengers (e.g. VK Teams).

Please comment if you can still reproduce on **5.0.8**.
