### ISSUE TITLE
В последних версиях allure, в summary.json, отсутствует ключ duration внутри time. Общая длительность тестов находится за ключом sumDuration.

### ISSUE THREAD

**Issue by ReachHeaven** [qa-guru/allure-notifications#183]
summary.json: 
{"reportName":"Allure Report","testRuns":[],"statistic":{"failed":3,"broken":0,"skipped":0,"passed":10,"unknown":0,"total":13},"time":{"minDuration":9533,"maxDuration":55521,"sumDuration":443172}}
Output: 
2023-06-05 12:25:50 ERROR Application:32 - Duration can't be null!
guru.qa.allure.notifications.exceptions.InvalidArgumentException: Duration can't be null!
        at guru.qa.allure.notifications.formatters.Formatters.formatTime(Formatters.java:20)
        at guru.qa.allure.notifications.template.data.SummaryData.map(SummaryData.java:32)
        at guru.qa.allure.notifications.template.data.MessageData.getValues(MessageData.java:36)
        at guru.qa.allure.notifications.template.MessageTemplate.of(MessageTemplate.java:42)
        at guru.qa.allure.notifications.template.TelegramTemplate.create(TelegramTemplate.java:17)
        at guru.qa.allure.notifications.clients.telegram.TelegramClient.sendPhoto(TelegramClient.java:42)
        at guru.qa.allure.notifications.clients.Notification.send(Notification.java:23)
        at guru.qa.allure.notifications.Application.startApplication(Application.java:30)
        at guru.qa.allure.notifications.Application.main(Application.java:16)
Workaround: 
<img width="1440" alt="image" src="https://github.com/qa-guru/allure-notifications/assets/22289240/e1b45b97-198e-4e58-afc6-d3219461c5c5">

**Comment by valfirst** [comment]
@ReachHeaven which version of allure do you use?  and which adaptor?

**Comment by ReachHeaven** [comment]
@valfirst 

allure version 2.22.1
allure-notifications 4.2.1
allure-maven 2.12.0

**Comment by valfirst** [comment]
@ReachHeaven it's still not enough to reproduce the issue
