### ISSUE TITLE
Error when sending reports to slack.

### ISSUE THREAD

**Issue by SuNseTgReeN** [qa-guru/allure-notifications#273]
### Discussed in https://github.com/qa-guru/allure-notifications/discussions/272

<div type='discussions-op-text'>

<sup>Originally posted by **SuNseTgReeN** June 11, 2024</sup>
When sending the report, I get the following error:
```
2024-06-11 11:32:44 INFO  Notification:44 - Sending message...
2024-06-11 11:32:44 ERROR Application:30 - null
java.lang.NullPointerException: null
	at kong.unirest.BodyPart.<init>(BodyPart.java:40) ~[allure-notifications-4.6.1.jar:?]
	at kong.unirest.ParamPart.<init>(ParamPart.java:[37](https://git.appkode.ru/qa_team/liteforex-postman-api-tests/-/jobs/1074937#L37)) ~[allure-notifications-4.6.1.jar:?]
	at kong.unirest.ParamPart.<init>(ParamPart.java:33) ~[allure-notifications-4.6.1.jar:?]
	at kong.unirest.HttpRequestMultiPart.field(HttpRequestMultiPart.java:48) ~[allure-notifications-4.6.1.jar:?]
	at guru.qa.allure.notifications.clients.slack.SlackClient.sendPhoto(SlackClient.java:[38](https://git.appkode.ru/qa_team/liteforex-postman-api-tests/-/jobs/1074937#L38)) ~[allure-notifications-4.6.1.jar:?]
	at guru.qa.allure.notifications.clients.Notification.send(Notification.java:46) ~[allure-notifications-4.6.1.jar:?]
	at guru.qa.allure.notifications.Application.startApplication(Application.java:28) [allure-notifications-4.6.1.jar:?]
	at guru.qa.allure.notifications.Application.main(Application.java:15) [allure-notifications-4.6.1.jar:?]
Cleaning up project directory and file based variables
00:07
ERROR: Job failed: exit code 1
```
At the same time, sending a message in telegram works in the same pipeline. I set up the bot according to [this](https://github.com/qa-guru/allure-notifications/wiki/Stack-configuration ) to the guide. Can you tell me what I could have done wrong, and how to solve this problem?</div>

**Comment by SuNseTgReeN** [comment]
It was found out that slack replaced the methods of sending messages. Now 3 new methods are used instead of 1.

**Comment by valfirst** [comment]
@SuNseTgReeN could you please provide more details?

**Comment by oleksandrso** [comment]
Some time ago slack changed the api for working with images. as a result there is a problem with sending notifications to slack for newly created bots

**Comment by a-havrysh** [comment]
Good day! 

Tell me, is there a plan to update allure-notifications in Slack? Previously, there was 1 url for connection, now there are 3, will you update allure-notifications for these needs?

https://api.slack.com/methods/files.upload

**Comment by valfirst** [comment]
@a-havrysh please feel free to propose PR

**Comment by Phoenix124** [comment]
@valfirst review please https://github.com/qa-guru/allure-notifications/pull/292
