### ISSUE TITLE
Setup for e-mail notification needs bot.token (and chat.id)

### ISSUE THREAD

**Issue by xt4k** [qa-guru/allure-notifications#49]
If setup application to send reports to email and skip bot.token 
then step with allure notification report is failed with error
====
Exception in thread "main" com.github.guru.qa.allure.notifications.exceptions.ArgumentNotProvidedException: Argument bot.token is not provided.
	at com.github.guru.qa.allure.notifications.utils.SettingsHelper.lambda$botToken$0(SettingsHelper.java:19)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at com.github.guru.qa.allure.notifications.utils.SettingsHelper.botToken(SettingsHelper.java:18)
	at com.github.guru.qa.allure.notifications.utils.Journal.settings(Journal.java:33)
	at com.github.guru.qa.allure.notifications.Application.main(Application.java:15)
====
The same situation when skipped chat.id

**Comment by kadehar** [comment]
Will be fixed in 3.0.0
